name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: pwsh

jobs:
  build-test:
    runs-on: windows-latest

    env:
      Project_Path: src\EarthBackground.csproj
      Test_Project_Path: EarthBackground.Tests\EarthBackground.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: |
        dotnet restore $env:Project_Path
        dotnet restore $env:Test_Project_Path

    - name: Build
      run: dotnet build $env:Test_Project_Path --configuration Release --no-restore

    - name: Test
      run: dotnet test $env:Test_Project_Path --configuration Release --no-build --verbosity normal
